apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
  namespace: oih-dev-ns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/localVolume/
